# -*- coding: utf-8 -*-
"""ch3-2-二維成績陣列實作.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1crrPQIIb7VCZik05mp-dKkDynzs5s-aP
"""

s = [[90,85,92,0],[95,91,96,0],[82,80,88,0],[91,90,85,0],[80,95,82,0]]
for i in range(5):
  for j in range(3):
    s[i][3] = s[i][3] + s[i][j]
  print(s[i][3])

s = [[90,85,92,0],[95,91,96,0],[82,80,88,0],[91,90,85,0],[80,95,82,0]]
for i in range(len(s)):
  sum = 0
  for j in range(len(s[0])-1):
    sum = sum + s[i][j]
  s[i][3] = sum

for i in range(len(s)):
  print(s[i][3])